---
- name: install packages
  hosts: target_hosts
  become: true
  tasks:
    - block:
      - name: install python2-dnf
        yum: name=python2-dnf state=present
      - name: install packages
        dnf: name={{item}} state=present
        with_items:
          - sl
          - libselinux-python
          - cowsay
          - vim-enhanced
      when: ansible_distribution == "Fedora"

- name: deploy files
  hosts: target_hosts
  become: false
  tasks:
    - name: deploy the vimrc
      copy: src=../vimrc dest={{ansible_user_dir}}/.vimrc
