---
- name: root configuration
  hosts: target_hosts
  become: true
  tasks:
    - block:
      - name: install packages
        dnf:
          name:
            - sl
            - libselinux-python
            - cowsay
            - vim-enhanced
            - fedora-packager
            - git-core-doc
            - chrony
          state: present
      - name: chrony service
        service: name=chronyd state=started enabled=yes
      when: ansible_distribution == "Fedora"
    - block:
      - name: install relevant repositories
        yum:
          name:
            - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            - centos-release-scl
          state: present
      - name: install packages
        yum:
          name:
            - sl
            - cowsay
            - fedora-packager
            - git
            - vim-enhanced
            - ntp
            - screen
            - irssi
            - rh-python36
            - bash-completion
          state: present
      - name: remove chrony
        yum: name=chrony state=absent
      - name: start ntp service
        service: name=ntpd state=started enabled=yes
      - name: update all packages
        yum:
          name: "*"
          state: latest
      - block:
        - name: install hyperv daemons
          yum:
            name:
              - hyperv-tools
              - hyperv-daemons
            state: present
        - name: enable hyperv services
          service:
            name: "{{item}}"
            state: started
            enabled: true
          with_items:
            - hypervkvpd
            - hypervvssd
            - hypervfcopyd
        when: ansible_virtualization_type == "VirtualPC"
      when: ansible_distribution == "CentOS"

- name: deploy files
  hosts: target_hosts
  become: false
  tasks:
    - name: deploy the vimrc
      copy: src=../vimrc dest={{ansible_user_dir}}/.vimrc
    - name: set up git
      copy: src=../gitconfig dest={{ansible_user_dir}}/.gitconfig mode=0644
    - name: ensure the ssh directory exists
      file: dest={{ansible_user_dir}}/.ssh state=directory mode=0700
    - name: ssh config
      copy: src=../ssh-config dest={{ansible_user_dir}}/.ssh/config
