---
- name: install packages
  hosts: target_hosts
  become: true
  tasks:
    - block:
      - name: install python2-dnf
        yum: name=python2-dnf state=present
      - name: install packages
        dnf: name={{item}} state=present
        with_items:
          - sl
          - libselinux-python
          - cowsay
          - vim-enhanced
          - fedora-packager
          - git-core-doc
      when: ansible_distribution == "Fedora"
    - block:
      - name: install epel repository
        yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present
      - name: install packages
        yum: name={{item}} state=present
        with_items:
          - sl
          - cowsay
          - fedora-packager
          - git
          - vim-enhanced
      when: ansible_distribution == "CentOS"

- name: deploy files
  hosts: target_hosts
  become: false
  tasks:
    - name: deploy the vimrc
      copy: src=../vimrc dest={{ansible_user_dir}}/.vimrc
    - name: set up git
      copy: src=../gitconfig dest={{ansible_user_dir}}/.gitconfig mode=0644
